#!/bin/bash

#!/bin/bash

set -eo pipefail

help() {
	echo "USAGE: $0 [-a <TARGET_ARCH>] [-c <CONFIG_FILE> -i <IMAGE_NAME>] -t <OUTPUT_TYPE>..."
	exit 1
}

[[ -z "$1" ]] && help

types=()

while getopts "a:c:i:t:h" flag; do
	case $flag in
		a) TARGET=$OPTARG ;;
		c) CONFIG=$OPTARG ;;
		i) IMAGE=$OPTARG ;;
		t) types+=("$OPTARG") ;;
		h) help ;;
		*) help ;;
	esac
done

# Add input validation for required arguments
[[ -z "$IMAGE" ]] && {
	echo "Error: Image name is missing."
	help
	exit 1
}

sudo podman pull ${TARGET:+--arch "$TARGET"} "$IMAGE"

podman_run_args=(
	--rm
	-t
	--privileged
	--pull=newer
	--network host
	--security-opt label=type:unconfined_t
)

if [[ -n $CONFIG ]]; then
	podman_run_args+=(
		-v ./$CONFIG:/config.toml:ro
	)
fi

podman_run_args+=(
	-v .:/output
	-v /var/lib/containers/storage:/var/lib/containers/storage
	quay.io/centos-bootc/bootc-image-builder:latest
)

for type in "${types[@]}"; do
	podman_run_args+=("--type" "$type")
done

if [[ -n "$TARGET" ]]; then
	podman_run_args+=("--target-arch" "$TARGET")
fi

podman_run_args+=(
	--rootfs ext4
	--chown "$UID:$GID"
	"$IMAGE"
)

sudo podman run ${podman_run_args[@]}
