#!/bin/env bash

set -eu
echo "#!/bin/bash" > firewall-setup.sh
firewall-cmd --get-zones | sed -E -e 's/[[:blank:]]+/\n/g' > zones.list || true

echo "Firewall backup"
echo ""
echo "Reading zones..."
echo ""

while read -r zones; do
	echo "Backing up zone ${zones}:"
	{
		echo "# Deleting existing zone ${zones}"
		echo "firewall-cmd --permanent --delete-zone=${zones}"
		echo "# Creating new zone ${zones}"
		echo "firewall-cmd --permanent --new-zone=${zones}"
		echo "- Rich Rules"
		echo "# Adding rich rules for zone ${zones}"
	} >> firewall-setup.sh

	firewall-cmd --list-all --zone="${zones}" | grep 'rule ' |
		sed -e 's/^[ \t]*//' > richrule.list || true
	sed -i -e "s/$/'/" richrule.list
	sed -i -e "s/^/'/" richrule.list
	sed -i -e "s/^/firewall-cmd --zone=${zones} --permanent --add-rich-rule=/" \
		richrule.list
	cat richrule.list >> firewall-setup.sh

	echo "- Ports"
	echo "# Adding ports for zone ${zones}" >> firewall-setup.sh
	firewall-cmd --list-all --zone="${zones}" | grep ports | grep 'udp\|tcp' |
		awk -F"ports:" '{print$2}' | sed -E -e 's/[[:blank:]]+/\n/g' |
		sed '/^$/d' > ports.list || true
	sed -i -e "s/^/firewall-cmd --permanent --zone=${zones} --add-port=/" \
		ports.list
	cat ports.list >> firewall-setup.sh

	echo "- Sources"
	echo "# Adding sources for zone ${zones}" >> firewall-setup.sh
	firewall-cmd --list-all --zone="${zones}" | grep sources |
		awk -F"sources:" '{print$2}' | sed -E -e 's/[[:blank:]]+/\n/g' |
		sed '/^$/d' > sources.list || true
	sed -i -e "s/^/firewall-cmd --permanent --zone=${zones} --add-port=/" \
		ports.list
	cat sources.list >> firewall-setup.sh

	echo "- Services"
	echo "# Adding services for zone ${zones}" >> firewall-setup.sh
	firewall-cmd --list-all --zone="${zones}" | grep services |
		awk -F"services:" '{print$2}' | sed -E -e 's/[[:blank:]]+/\n/g' |
		sed '/^$/d' > services.list || true
	sed -i -e "s/^/firewall-cmd --permanent --zone=${zones} --add-service=/" \
		services.list
	cat services.list >> firewall-setup.sh

	echo "" >> firewall-setup.sh
done < zones.list
echo "" >> firewall-setup.sh

echo "Reading Policies..."
echo ""
firewall-cmd --get-policies | sed -E -e 's/[[:blank:]]+/\n/g' > policies.list ||
	true

while read -r policies; do
	echo "Backing up policy ${policies}:"
	{
		echo "# Deleting existing policy ${policies}"
		echo "firewall-cmd --permanent --delete-policy=${policies}"

		echo "# Creating new policy ${policies}"
		echo "firewall-cmd --permanent --new-policy=${policies}"
	} >> firewall-setup.sh

	echo "- Rich rules"
	echo "# Adding rich rules for policy ${policies}" >> firewall-setup.sh
	firewall-cmd --list-all --policy="${policies}" | grep 'rule ' |
		sed -e 's/^[ \t]*//' > pol_richrule.list || true
	sed -i -e "s/$/'/" pol_richrule.list
	sed -i -e "s/^/'/" pol_richrule.list
	sed -i -e \
		"s/^/firewall-cmd --policy=${policies} --permanent --add-rich-rule=/" \
		pol_richrule.list
	cat pol_richrule.list >> firewall-setup.sh

	echo "- Ports"
	echo "# Adding ports for policy ${policies}" >> firewall-setup.sh
	firewall-cmd --list-all --policy="${policies}" | grep ports | grep 'udp\|tcp' |
		awk -F"ports:" '{print$2}' | sed -E -e 's/[[:blank:]]+/\n/g' |
		sed '/^$/d' > pol_ports.list || true
	sed -i -e "s/^/firewall-cmd --permanent --policy=${policies} --add-port=/" \
		pol_ports.list
	cat pol_ports.list >> firewall-setup.sh

	echo "- Services"
	echo "# Adding services for policy ${policies}" >> firewall-setup.sh
	firewall-cmd --list-all --policy="${policies}" | grep services |
		awk -F"services:" '{print$2}' | sed -E -e 's/[[:blank:]]+/\n/g' |
		sed '/^$/d' > pol_services.list || true
	sed -i -e \
		"s/^/firewall-cmd --permanent --policy=${policies} --add-service=/" \
		pol_services.list
	cat pol_services.list >> firewall-setup.sh

	echo "- Ingress zones"
	echo "# Setting ingress-zones for policy ${policies}" >> firewall-setup.sh
	firewall-cmd --list-all --policy="${policies}" | grep ingress-zones |
		awk -F"ingress-zones:" '{print$2}' | sed -E -e 's/[[:blank:]]+/\n/g' |
		sed '/^$/d' > pol_ingress.list || true
	sed -i -e \
		"s/^/firewall-cmd --permanent --policy=${policies} --add-egress-zone=/" \
		pol_ingress.list
	cat pol_ingress.list >> firewall-setup.sh

	echo "- Egress zones"
	echo "# Setting egress-zones for policy ${policies}" >> firewall-setup.sh
	firewall-cmd --list-all --policy="${policies}" | grep egress-zones |
		awk -F"egress-zones:" '{print$2}' | sed -E -e 's/[[:blank:]]+/\n/g' |
		sed '/^$/d' > pol_egress.list || true
	sed -i -e \
		"s/^/firewall-cmd --permanent --policy=${policies} --add-egress-zone=/" \
		pol_egress.list
	cat pol_egress.list >> firewall-setup.sh

	echo "- Targets"
	echo "# Setting target for policy ${policies}" >> firewall-setup.sh
	TARGET=$(firewall-cmd --permanent --policy="${policies}" --get-target)
	echo "firewall-cmd --permanent --policy=${policies} --set-target=${TARGET}" \
		>> firewall-setup.sh
	echo "" >> firewall-setup.sh
done < policies.list

echo "firewall-cmd --reload" >> firewall-setup.sh
rm -rf ./*.list
