#!/bin/bash

# SPDX-License-Identifier: GPL-2.0

# Rebuild source RPM Packages for the specified platform using the
# docker.io/dirk1980/rpm-crossbuild:latest Podman image.
# Actually supported by the image are linux/amd64 and linux/arm64.

# Copyright 2024 by Dirk Gottschalk

# Print a hopefully useful help text.

help() {
	cat <<EOF
Usage: rpm-crossbuild -i <directory> -o <directory> -p <platform>

Options:
    -d <directory>        Working directory (mandatory)
    -p <platform>         Target platform (if not host platform)
    -h                    Show this help
EOF
	exit 1
}

# Check command line options
while getopts "p:i:o:h" flag; do
	case "${flag}" in
	d) data=${OPTARG} ;;
	p) platform=${OPTARG} ;;
	h) help ;;
	*) help ;;
	esac
done

if [[ ! -d $data ]]; then
	echo "$data is not a directory."
	exit 1
fi

args=(
	--rm
	-it
	--security-opt label=type:unconfined_t
	--pull=newer
)

if [[ -n "$platform" ]]; then
	args+=("--platform" "$platform")
fi

args+=(
	-v $data:/datadir
	docker.io/dirk1980/rpm-crossbuild:latest
)

podman run $args
